version: '3'
services:
  nginx:
    image: nginx:1.25.0
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    environment:
      - MESSAGE='HOLA MUCHACH@S'
    depends_on:
      - app
      - app2
    networks:
      - vpc
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - MESSAGE='ESTAS EN PROD'
    volumes:
      - ./nginx2.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8000:8000
    networks:
      - vpc
  app2:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - MESSAGE='ESTAS EN QA'
    volumes:
      - ./nginx2.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:8000
    networks:
      - vpc
networks:
  vpc:     